# Data Extraction

In [112]:
import obspy, io, subprocess, utils, os
from pathlib import Path
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# import obspy.core.utcdatetime as utc
# from obspy.clients.fdsn import Client
# from eqcct.stream import st_predictor
# from eqcct import plot_traces

WIN_SIZE = 60               # Window size in seconds. Same window size used in EQCCT paper
PRE_EVENT_BUFFER = 5        # Number of seconds from start of window until first pick
POST_EVENT_BUFFER = 5       # Number of seconds from last pick until end of window

ISUH_IP_ADDR = "http://128.214.169.201:8080"
WAVEFORM_DIR = "waveforms"
PRED_DIR = "predictions"

## Opening large mseed files
`obspy.read()` cannot directly read mini-SEED files that are larger than 2048 MB. Read the file in chunks instead ([link](https://github.com/obspy/obspy/pull/1419#issuecomment-221582369) to github issue).

Note on `record_len`: A record is a unit of data in the miniSEED format. A record consists of a certain number of data points in the waveform. Typical record lengths for raw data generation and archiving are between 256 and 4096 bytes ([FDSN docs](https://docs.fdsn.org/projects/miniseed3/en/latest/definition.html#:~:text=typical%20record%20lengths%20for%20raw%20data%20generation%20and%20archiving%20are%20recommended%20to%20be%20in%20the%20range%20of%20256%20and%204096%20bytes)).

In [3]:
mseed_filename = "HE_020125_030125.mseed" # Queried from ISUH FDSNWS. It is a 3.7GB file containing waveforms from HE network from 2-3 Jan 2025
data_dir = Path("data")

record_len = 512
chunksize = 100000 * record_len
with io.open(data_dir / mseed_filename, "rb") as fh:
    while True:
        with io.BytesIO() as buf:
            c = fh.read(chunksize)
            if not c:
                break
            buf.write(c)
            buf.seek(0, 0)
            st = obspy.read(buf)
        # Do something useful!
        print(st)
        break # We just want to see the first stream from the mseed file

2 Trace(s) in Stream:
HE.OBF8..HHE | 2025-01-01T23:59:59.568000Z - 2025-01-03T00:00:00.748000Z | 250.0 Hz, 21600296 samples
HE.OBF8..HHN | 2025-01-01T23:59:58.808000Z - 2025-01-02T07:26:55.188000Z | 250.0 Hz, 6704096 samples

## Querying waveform data from ISUH FDSNWS

To query ISUH FDSNWS dataselect service, ensure your device is connected to the university's network. Eduroam does not work, but wired connections on devices at the university do.

In [ ]:
from obspy.clients.fdsn import Client
from obspy import UTCDateTime


client = Client("http://128.214.169.201:8080") # ISUH FDSNWS IP address

start_time = UTCDateTime("2025-01-01T23:59:59.568000Z")
end_time = UTCDateTime("2025-01-03T00:00:00.748000Z")

st = client.get_waveforms("HE", "OBF8", "*", "HHZ", start_time, end_time)

st.plot()

## Creating waveform dataset

#### 1. Extract pick information from quakeML files into `df_pick`

In [93]:
data_dir = Path("data")

paths = {
    "earthquakes": data_dir / "earthquakes2025.qkml",
    "explosions": data_dir / "explosions2025.qkml",
    "probable_explosions": data_dir / "probable_explosions2025.qkml",
}

catalogs = {}
for name, path in paths.items():
    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path.resolve()}")
    catalogs[name] = obspy.read_events(str(path))
    print(f"{name}: {len(catalogs[name])} events loaded from {path.name}")

# Dataframe of all earthquake, explosion and probable_explosion picks               
df_picks = utils.extract_picks(catalogs)
# df_picks.to_csv("picks.csv") # Export to csv for possible debugging

print(f"Total number of picks: {len(df_picks)}")
print(df_picks["Event type"].value_counts().to_frame(name="Number of picks"))
df_picks.head()

earthquakes: 328 events loaded from earthquakes2025.qkml
explosions: 599 events loaded from explosions2025.qkml
probable_explosions: 1455 events loaded from probable_explosions2025.qkml
Total number of picks: 54134
                     Number of picks
Event type
probable_explosions            32720
explosions                     14281
earthquakes                     7133

,Event id,SEED string,Pick type,Event type,Pick time
0,smi:fi.isuh/event/1490639,UP.LANU..BHZ,P,earthquakes,2025-01-01T09:22:01.256470Z
1,smi:fi.isuh/event/1490639,UP.LANU..BHZ,S,earthquakes,2025-01-01T09:22:07.069410Z
2,smi:fi.isuh/event/1490639,HE.HEF..BHZ,P,earthquakes,2025-01-01T09:22:02.651570Z
3,smi:fi.isuh/event/1490639,HE.HEF..BHZ,S,earthquakes,2025-01-01T09:22:09.394590Z
4,smi:fi.isuh/event/1490639,FN.KLF..BHZ,P,earthquakes,2025-01-01T09:22:07.766970Z

#### 2. Identify windows to query waveforms from ISUH FDSNWS

Note about events:
* Each seismic event has zero or more P picks, and zero or more S picks
* Multiple stations can produce picks for the same event
* Therefore, a window will be uniquely identified by its event-station tuple (`Event id`, `SEED string short`)

Window definition:
* Each window should contain one P pick and one S pick, similar to the STEAD dataset used in benchmarking EQCCT. The STEAD dataset uses 60s windows.
* But if P and S arrival times may be too far from each other, each pick will be put in its own separate query

In [ ]:
# Select earthquake picks
df_picks_eq = df_picks[df_picks["Event type"] == "earthquakes"]

# Remove channel ID from the SEED string, so that the shortened SEED string can identify stations
df_picks_eq["SEED string short"] = df_picks_eq["SEED string"].str.rsplit(".", n=1).str[0] 


# Report how many P and S picks are made at each event-station 
num_PS_picks = []
for (event_id, seed_string), df_group in df_picks_eq.groupby(["Event id", "SEED string short"]):
    num_P_picks = int(df_group["Pick type"].str.startswith("P").sum())
    num_S_picks = int(df_group["Pick type"].str.startswith("S").sum())
    num_PS_picks.append((num_P_picks, num_S_picks))
print(pd.Series(num_PS_picks, name="(num P picks, num S picks)").value_counts().to_frame("Number of event-stations").reset_index())
print("")


# Time of the earliest pick (usually P) for an event-station
df_picks_eq["Event start"] = df_picks_eq.groupby(["Event id", df_picks_eq["SEED string short"]])["Pick time"].transform("min")

# Time of the latest pick (usually S) for an event-station
df_picks_eq["Event end"] = df_picks_eq.groupby(["Event id", df_picks_eq["SEED string short"]])["Pick time"].transform("max")

# Ensure that query window starts 5s before the first pick (usually P)
df_picks_eq["Win start"] = df_picks_eq["Event start"] - PRE_EVENT_BUFFER

# Ensure that query window is WIN_SIZE seconds long
df_picks_eq["Win end"] = df_picks_eq["Win start"] + WIN_SIZE


# Mask for P-S pairs that are too far (far pairs) to be contained by the window; Window too short to contain P, S, 5s buffer after S wave, and 5s buffer before P wave
mask_far_picks = df_picks_eq["Win end"] - POST_EVENT_BUFFER < df_picks_eq["Event end"]


# Report the number of far pairs
df_far_picks = df_picks_eq[mask_far_picks]
df_far_picks["P-S time diff (s)"] = df_far_picks["Event end"] - df_far_picks["Event start"] # Extract time difference between P and S picks for inspection

max_diff = max(df_picks_eq["Event end"] - df_picks_eq["Event start"])               # Max time diff between P-S pair
num_far_pairs = len(df_far_picks.value_counts(["Event id", "SEED string short"]))   # Number of far pairs

print(f"Max duration between P and S arrivals: {max_diff}s\n")
print(f"The window size is too short to contain P, S picks, and buffers for these events ({num_far_pairs} far pairs, {len(df_far_picks)} far picks):")


# Proceed to put each far picks into their own separate windows
df_picks_eq.loc[mask_far_picks, "Win start"] = df_picks_eq.loc[mask_far_picks, "Pick time"] - PRE_EVENT_BUFFER
df_picks_eq.loc[mask_far_picks, "Win end"] = df_picks_eq.loc[mask_far_picks, "Win start"] + WIN_SIZE
df_picks_eq.loc[mask_far_picks, "Event id"] = df_picks_eq.loc[mask_far_picks, "Event id"] + df_picks_eq.loc[mask_far_picks, "Pick type"] # Each window will be identified by event-station fields later, but we need to distinguish between windows of far picks since they have their own separate windows, so we add suffix for differentiation


# df_picks_eq.to_csv("eq_picks.csv", index=False)  # Save picks to csv for debugging

df_far_picks

  (num P picks, num S picks)  Number of event-stations
0                     (1, 1)                      2844
1                     (0, 1)                      1369
2                     (1, 0)                        46
3                     (1, 2)                         5
4                     (2, 1)                         3
5                     (0, 2)                         3

Max duration between P and S arrivals: 86.70201s

The window size is too short to contain P, S picks, and buffers for these events (16 far pairs, 33 far picks):

,Event id,SEED string,Pick type,Event type,Pick time,SEED string short,Event start,Event end,Win start,Win end,P-S time diff (s)
256,smi:fi.isuh/event/1491766,NS.STOK..?HZ,P,earthquakes,2025-01-12T20:07:08.896530Z,NS.STOK.,2025-01-12T20:07:08.896530Z,2025-01-12T20:08:05.293930Z,2025-01-12T20:07:03.896530Z,2025-01-12T20:08:03.896530Z,56.3974
257,smi:fi.isuh/event/1491766,NS.STOK..?HZ,S,earthquakes,2025-01-12T20:08:05.293930Z,NS.STOK.,2025-01-12T20:07:08.896530Z,2025-01-12T20:08:05.293930Z,2025-01-12T20:07:03.896530Z,2025-01-12T20:08:03.896530Z,56.3974
258,smi:fi.isuh/event/1491766,UP.HEMU..BHZ,P,earthquakes,2025-01-12T20:07:20.381200Z,UP.HEMU.,2025-01-12T20:07:20.381200Z,2025-01-12T20:08:26.692320Z,2025-01-12T20:07:15.381200Z,2025-01-12T20:08:15.381200Z,66.31112
259,smi:fi.isuh/event/1491766,UP.HEMU..BHZ,S,earthquakes,2025-01-12T20:08:26.692320Z,UP.HEMU.,2025-01-12T20:07:20.381200Z,2025-01-12T20:08:26.692320Z,2025-01-12T20:07:15.381200Z,2025-01-12T20:08:15.381200Z,66.31112
260,smi:fi.isuh/event/1491766,UP.HUSU..BHZ,P,earthquakes,2025-01-12T20:07:27.662460Z,UP.HUSU.,2025-01-12T20:07:27.662460Z,2025-01-12T20:08:39.484710Z,2025-01-12T20:07:22.662460Z,2025-01-12T20:08:22.662460Z,71.82225
261,smi:fi.isuh/event/1491766,UP.HUSU..BHZ,S,earthquakes,2025-01-12T20:08:39.484710Z,UP.HUSU.,2025-01-12T20:07:27.662460Z,2025-01-12T20:08:39.484710Z,2025-01-12T20:07:22.662460Z,2025-01-12T20:08:22.662460Z,71.82225
262,smi:fi.isuh/event/1491766,UP.NRTU..BHZ,P,earthquakes,2025-01-12T20:07:35.279830Z,UP.NRTU.,2025-01-12T20:07:35.279830Z,2025-01-12T20:08:51.486290Z,2025-01-12T20:07:30.279830Z,2025-01-12T20:08:30.279830Z,76.20646
263,smi:fi.isuh/event/1491766,UP.NRTU..BHZ,S,earthquakes,2025-01-12T20:08:51.486290Z,UP.NRTU.,2025-01-12T20:07:35.279830Z,2025-01-12T20:08:51.486290Z,2025-01-12T20:07:30.279830Z,2025-01-12T20:08:30.279830Z,76.20646
264,smi:fi.isuh/event/1491766,HE.ECKF..CZ,P,earthquakes,2025-01-12T20:07:37.052100Z,HE.ECKF.,2025-01-12T20:07:37.052100Z,2025-01-12T20:08:53.717110Z,2025-01-12T20:07:32.052100Z,2025-01-12T20:08:32.052100Z,76.66501
265,smi:fi.isuh/event/1491766,HE.ECKF..CZ,S,earthquakes,2025-01-12T20:08:53.717110Z,HE.ECKF.,2025-01-12T20:07:37.052100Z,2025-01-12T20:08:53.717110Z,2025-01-12T20:07:32.052100Z,2025-01-12T20:08:32.052100Z,76.66501
266,smi:fi.isuh/event/1491766,HE.KPF..BHZ,P,earthquakes,2025-01-12T20:07:47.672140Z,HE.KPF.,2025-01-12T20:07:47.672140Z,2025-01-12T20:09:14.374150Z,2025-01-12T20:07:42.672140Z,2025-01-12T20:08:42.672140Z,86.70201
267,smi:fi.isuh/event/1491766,HE.KPF..BHZ,S,earthquakes,2025-01-12T20:09:14.374150Z,HE.KPF.,2025-01-12T20:07:47.672140Z,2025-01-12T20:09:14.374150Z,2025-01-12T20:07:42.672140Z,2025-01-12T20:08:42.672140Z,86.70201
1075,smi:fi.isuh/event/1496200,HE.ECKF..CZ,P,earthquakes,2025-02-19T15:17:22.600450Z,HE.ECKF.,2025-02-19T15:17:22.600450Z,2025-02-19T15:18:14.261130Z,2025-02-19T15:17:17.600450Z,2025-02-19T15:18:17.600450Z,51.66068
1076,smi:fi.isuh/event/1496200,HE.ECKF..CZ,S,earthquakes,2025-02-19T15:18:14.261130Z,HE.ECKF.,2025-02-19T15:17:22.600450Z,2025-02-19T15:18:14.261130Z,2025-02-19T15:17:17.600450Z,2025-02-19T15:18:17.600450Z,51.66068
1077,smi:fi.isuh/event/1496200,HE.ECKF..CZ,SG,earthquakes,2025-02-19T15:18:14.260000Z,HE.ECKF.,2025-02-19T15:17:22.600450Z,2025-02-19T15:18:14.261130Z,2025-02-19T15:17:17.600450Z,2025-02-19T15:18:17.600450Z,51.66068
1078,smi:fi.isuh/event/1496200,UP.ARNU..BHZ,P,earthquakes,2025-02-19T15:17:23.428530Z,UP.ARNU.,2025-02-19T15:17:23.428530Z,2025-02-19T15:18:14.380760Z,2025-02-19T15:17:18.428530Z,2025-02-19T15:18:18.428530Z,50.95223
1079,smi:fi.isuh/event/1496200,UP.ARNU..BHZ,SG,earthquakes,2025-02-19T15:18:14.380760Z,UP.ARNU.,2025-02-19T15:17:23.428530Z,2025-02-19T15:18:14.380760Z,2025-02-19T15:17:18.428530Z,2025-02-19T15:18:18.428530Z,50.95223
1084,smi:fi.isuh/event/1496200,HE.KORF..CZ,P,earthquakes,2025-02-19T15:17:35.773720Z,HE.KORF.,2025-02-19T15:17:35.773720Z,2025-02-19T15:18:40.895490Z,2025-02-19T15:17:30.773720Z,2025-02-19T15:18:30.773720Z,65.12177
1085,smi:fi.isuh/event/1496200,HE.KORF..CZ,SG,earthquakes,2025-02-19T15:18:40.895490Z,HE.KORF.,2025-02-19T15:17:35.773720Z,2025-02-19T15:18:40.895490Z,2025-02-19T15:17:30.773720Z,2025-02-19T15:18:30.773720Z,65.12177
1087,smi:fi.isuh/event/1496200,HE.RAF..BHZ,P,earthquakes,2025-02-19T15:17:40.682820Z,HE.RAF.,2025-02-19T15:17:40.682820Z,2025-02-19T15:18:50.943920Z,2025-02-19T15:17:35.682820Z,2025-02-19T15:18:35.682820Z,70.2611
1088,smi:fi.isuh/event/1496200,HE.RAF..BHZ,SG,earthquakes,2025-02-19T15:18:50.943920Z,HE.RAF.,2025-02-19T15:17:40.682820Z,2025-02-19T15:18:50.943920Z,2025-02-19T15:17:35.682820Z,2025-02-19T15:18:35.682820Z,70.2611
1091,smi:fi.isuh/event/1496200,NS.LENS..?HZ,P,earthquakes,2025-02-19T15:17:45.177270Z,NS.LENS.,2025-02-19T15:17:45.177270Z,2025-02-19T15:18:38.795160Z,2025-02-19T15:17:40.177270Z,2025-02-19T15:18:40.177270Z,53.61789
1092,smi:fi.isuh/event/1496200,NS.LENS..?HZ,S,earthquakes,2025-02-19T15:18:38.795160Z,NS.LENS.,2025-02-19T15:17:45.177270Z,2025-02-19T15:18:38.795160Z,2025-02-19T15:17:40.177270Z,2025-02-19T15:18:40.177270Z,53.61789
1093,smi:fi.isuh/event/1496200,HE.TVF..BHZ,P,earthquakes,2025-02-19T15:17:47.381770Z,HE.TVF.,2025-02-19T15:17:47.381770Z,2025-02-19T15:18:41.986020Z,2025-02-19T15:17:42.381770Z,2025-02-19T15:18:42.381770Z,54.60425
1094,smi:fi.isuh/event/1496200,HE.TVF..BHZ,S,earthquakes,2025-02-19T15:18:41.986020Z,HE.TVF.,2025-02-19T15:17:47.381770Z,2025-02-19T15:18:41.986020Z,2025-02-19T15:17:42.381770Z,2025-02-19T15:18:42.381770Z,54.60425
1096,smi:fi.isuh/event/1496200,NS.NSS..?HZ,P,earthquakes,2025-02-19T15:17:53.996790Z,NS.NSS.,2025-02-19T15:17:53.996790Z,2025-02-19T15:18:54.487500Z,2025-02-19T15:17:48.996790Z,2025-02-19T15:18:48.996790Z,60.49071
1097,smi:fi.isuh/event/1496200,NS.NSS..?HZ,S,earthquakes,2025-02-19T15:18:54.487500Z,NS.NSS.,2025-02-19T15:17:53.996790Z,2025-02-19T15:18:54.487500Z,2025-02-19T15:17:48.996790Z,2025-02-19T15:18:48.996790Z,60.49071
3683,smi:fi.isuh/event/1514984,FN.KLF..BHZ,P,earthquakes,2025-07-14T04:58:47.701860Z,FN.KLF.,2025-07-14T04:58:47.701860Z,2025-07-14T04:59:42.577600Z,2025-07-14T04:58:42.701860Z,2025-07-14T04:59:42.701860Z,54.87574
3684,smi:fi.isuh/event/1514984,FN.KLF..BHZ,SB,earthquakes,2025-07-14T04:59:42.577600Z,FN.KLF.,2025-07-14T04:58:47.701860Z,2025-07-14T04:59:42.577600Z,2025-07-14T04:58:42.701860Z,2025-07-14T04:59:42.701860Z,54.87574
3685,smi:fi.isuh/event/1514984,UP.PAJU..BHZ,P,earthquakes,2025-07-14T04:58:47.920800Z,UP.PAJU.,2025-07-14T04:58:47.920800Z,2025-07-14T04:59:43.659950Z,2025-07-14T04:58:42.920800Z,2025-07-14T04:59:42.920800Z,55.73915
3686,smi:fi.isuh/event/1514984,UP.PAJU..BHZ,SB,earthquakes,2025-07-14T04:59:43.659950Z,UP.PAJU.,2025-07-14T04:58:47.920800Z,2025-07-14T04:59:43.659950Z,2025-07-14T04:58:42.920800Z,2025-07-14T04:59:42.920800Z,55.73915
3726,smi:fi.isuh/event/1515089,FN.KLF..BHZ,P,earthquakes,2025-07-15T05:17:04.405360Z,FN.KLF.,2025-07-15T05:17:04.405360Z,2025-07-15T05:17:59.608690Z,2025-07-15T05:16:59.405360Z,2025-07-15T05:17:59.405360Z,55.20333
3727,smi:fi.isuh/event/1515089,FN.KLF..BHZ,SB,earthquakes,2025-07-15T05:17:59.608690Z,FN.KLF.,2025-07-15T05:17:04.405360Z,2025-07-15T05:17:59.608690Z,2025-07-15T05:16:59.405360Z,2025-07-15T05:17:59.405360Z,55.20333

#### 3. Generating labels for waveforms

The labels are stored in a CSV file, with the same columns as EQCCTOne's prediction output csv file.

In [ ]:
# Column names copied from EQCCTOne's prediction output csv file
COLUMNS_Y = ["file_name", "network", "station", "instrument_type", "station_lat", "station_lon", "station_elv","p_arrival_time", "p_probability", "s_arrival_time", "s_probability"]

df_y = pd.DataFrame(columns=COLUMNS_Y)

# Generate labels for each window. Each window has either both P and S times, or only one of them
for (event_id, seed_string), df_group in df_picks_eq.groupby(["Event id", "SEED string"]):
    win_start = df_group["Win start"].iloc[0]
    win_end = df_group["Win end"].iloc[0]
    
    p_time, s_time = None, None
    # If the event-station has P picks, choose the arrival time of the first P pick
    if df_group["Pick type"].str.startswith("P").any(): 
        p_time = df_group[df_group["Pick type"].str.startswith("P")]["Pick time"].iloc[0] 
    else:
        p_time = np.nan
    
    # If the event-station has S picks, choose the arrival time of the first S pick
    if df_group["Pick type"].str.startswith("S").any():
        s_time = df_group[df_group["Pick type"].str.startswith("S")]["Pick time"].iloc[0] 
    else:
        s_time = np.nan
    
    seed_string = seed_string.replace("..", ".00.") # Fill in missing fields in SEED string with 00 to match eqcct's prediction output format
    
    file_name = seed_string + " | " + str(win_start) + " - " + str(win_end)
    row_df = pd.DataFrame([[file_name, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 
                            p_time, np.nan, s_time, np.nan]], columns=COLUMNS_Y)
    
    df_y = pd.concat([df_y, row_df])

# df_y.to_csv("eq_labels.csv", index=False) # Save picks to csv for debugging
df_y

,file_name,network,station,instrument_type,station_lat,station_lon,station_elv,p_arrival_time,p_probability,s_arrival_time,s_probability
0,FN.KLF.00.BHZ | 2025-01-01T09:22:02.766970Z - ...,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-01T09:22:07.766970Z,NaN,2025-01-01T09:22:17.997750Z,NaN
0,FN.RNF.00.BHZ | 2025-01-01T09:22:18.810700Z - ...,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-01T09:22:23.810700Z,NaN,2025-01-01T09:22:45.899900Z,NaN
0,FN.SGF.00.BHZ | 2025-01-01T09:22:12.997750Z - ...,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-01T09:22:17.997750Z,NaN,2025-01-01T09:22:36.134150Z,NaN
0,HE.HEF.00.BHZ | 2025-01-01T09:21:57.651570Z - ...,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-01T09:22:02.651570Z,NaN,2025-01-01T09:22:09.394590Z,NaN
0,NO.ARA0.00.?HZ | 2025-01-01T09:22:42.760040Z -...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-01T09:22:47.760040Z,NaN
...,...,...,...,...,...,...,...,...,...,...,...
0,HE.KY17.00.CZ | 2025-11-10T01:45:35.562920Z - ...,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-10T01:45:40.562920Z,NaN,2025-11-10T01:45:47.332480Z,NaN
0,HE.LOVF.00.CZ | 2025-11-10T01:45:32.088540Z - ...,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-10T01:45:37.088540Z,NaN,2025-11-10T01:45:41.443310Z,NaN
0,HE.PVF.00.CZ | 2025-11-10T01:45:30.303730Z - 2...,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-10T01:45:35.303730Z,NaN,2025-11-10T01:45:38.293170Z,NaN
0,HE.VJF.00.?HZ | 2025-11-10T01:45:40.102750Z - ...,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-10T01:45:45.102750Z,NaN,2025-11-10T01:45:55.778810Z,NaN
0,HE.VUOS.00.BHZ | 2025-11-10T01:45:49.140890Z -...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-10T01:45:54.140890Z,NaN

#### 4. Generating Predictions 
There are two options:

1. Query ISUH FDSNWS for mseed files to store locally OR
2. Query windows then output predictions iteratively without storing mseed files

In [102]:
# Generate windows to query, identified based on event id and station id (SEED string short)
df_windows = df_picks_eq.drop_duplicates(["Event id", "SEED string short"]) 

df_windows.to_csv("eq_windows.csv", index=False) # Save windows to CSV to run on eqcct in another virtual environment lol

##### 4a. Option 1: Query ISUH FDSNWS for mseed files

In [ ]:
# Use create_dataset.py utility from eqcctpro
for seed_string, start, end in zip(df_windows["SEED string short"], df_windows["Win start"], df_windows["Win end"]):
    print(seed_string)
    # create_dataset.py can only be used via command line
    cmd = ["python", "create_dataset.py", 
                    "--start", str(start), "--end", str(end), 
                    "--streams", seed_string,
                    "--host", ISUH_IP_ADDR,
                    "--output", WAVEFORM_DIR,
                    "--chunk", "1"] # chunk size (minutes)
    subprocess.run(cmd)

UP.LANU..
Total time: 2025-01-01T09:21:56.256470Z → 2025-01-01T09:22:07.069410Z  (10.81294 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250101T092156Z → 20250101T092207Z ===
  Fetching for: UP.LANU.*.*
  Warning: can't fetch UP.LANU.*.*: No data available for request.
HTTP Status code: 204
Detailed response of server:


  No data downloaded for this window.

All windows processed. Done.
HE.HEF..
Total time: 2025-01-01T09:21:57.651570Z → 2025-01-01T09:22:09.394590Z  (11.74302 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250101T092157Z → 20250101T092209Z ===
  Fetching for: HE.HEF.*.*
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092157Z_20250101T092209Z/HEF/HE.HEF..HHE__20250101T092157Z__20250101T092209Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092157Z_20250101T092209Z/HEF/HE.HEF..HHN__20250101T092157Z__20250101T092209Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092157Z_20250101T092209Z/HEF/HE.HEF..HHZ__20250101T092157Z__20250101T092209Z.mseed  (1 traces)

All windows processed. Done.
FN.KLF..
Total time: 2025-01-01T09:22:02.766970Z → 2025-01-01T09:22:17.997750Z  (15.23078 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250101T092202Z → 20250101T092217Z ===
  Fetching for: FN.KLF.*.*
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092202Z_20250101T092217Z/KLF/FN.KLF..BHE__20250101T092202Z__20250101T092217Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092202Z_20250101T092217Z/KLF/FN.KLF..BHN__20250101T092202Z__20250101T092217Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092202Z_20250101T092217Z/KLF/FN.KLF..BHZ__20250101T092202Z__20250101T092217Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092202Z_20250101T092217Z/KLF/FN.KLF..HHE__20250101T092202Z__20250101T092217Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092202Z_20250101T092217Z/KLF/FN.KLF..HHN__20250101T092202Z__20250101T092217Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092202Z_20250101T092217Z/KLF/FN.KLF..HHZ__20250101T092202Z__20250101T092217Z.mseed  (1 traces)

All windows processed. Done.
UP.PAJU..
Total time: 2025-01-01T09:22:05.092140Z → 2025-01-01T09:22:22.183070Z  (17.09093 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250101T092205Z → 20250101T092222Z ===
  Fetching for: UP.PAJU.*.*
  Warning: can't fetch UP.PAJU.*.*: No data available for request.
HTTP Status code: 204
Detailed response of server:


  No data downloaded for this window.

All windows processed. Done.
FN.SGF..
Total time: 2025-01-01T09:22:12.997750Z → 2025-01-01T09:22:36.134150Z  (23.1364 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250101T092212Z → 20250101T092236Z ===
  Fetching for: FN.SGF.*.*
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..HHZ__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..HHN__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..HHE__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..BHZ__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..BHN__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..BHE__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..LHZ__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..LHN__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..LHE__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..VHZ__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..VHN__20250101T092212Z__20250101T092236Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092212Z_20250101T092236Z/SGF/FN.SGF..VHE__20250101T092212Z__20250101T092236Z.mseed  (1 traces)

All windows processed. Done.
UP.ERTU..
Total time: 2025-01-01T09:22:13.695310Z → 2025-01-01T09:22:37.064220Z  (23.36891 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250101T092213Z → 20250101T092237Z ===
  Fetching for: UP.ERTU.*.*
  Warning: can't fetch UP.ERTU.*.*: No data available for request.
HTTP Status code: 204
Detailed response of server:


  No data downloaded for this window.

All windows processed. Done.
FN.RNF..
Total time: 2025-01-01T09:22:18.810700Z → 2025-01-01T09:22:45.899900Z  (27.0892 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250101T092218Z → 20250101T092245Z ===
  Fetching for: FN.RNF.*.*
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..HHZ__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..HHN__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..HHE__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..BHZ__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..BHN__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..BHE__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..LHZ__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..LHN__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..LHE__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..VHZ__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..VHN__20250101T092218Z__20250101T092245Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250101T092218Z_20250101T092245Z/RNF/FN.RNF..VHE__20250101T092218Z__20250101T092245Z.mseed  (1 traces)

All windows processed. Done.
NO.ARA0..
Total time: 2025-01-01T09:22:42.760040Z → 2025-01-01T09:22:47.760040Z  (5.0 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250101T092242Z → 20250101T092247Z ===
  Fetching for: NO.ARA0.*.*
  Warning: can't fetch NO.ARA0.*.*: No data available for request.
HTTP Status code: 204
Detailed response of server:


  No data downloaded for this window.

All windows processed. Done.
FN.KLF..
Total time: 2025-01-02T04:42:08.358870Z → 2025-01-02T04:42:15.937140Z  (7.57827 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250102T044208Z → 20250102T044215Z ===
  Fetching for: FN.KLF.*.*
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044208Z_20250102T044215Z/KLF/FN.KLF..BHE__20250102T044208Z__20250102T044215Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044208Z_20250102T044215Z/KLF/FN.KLF..BHN__20250102T044208Z__20250102T044215Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044208Z_20250102T044215Z/KLF/FN.KLF..BHZ__20250102T044208Z__20250102T044215Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044208Z_20250102T044215Z/KLF/FN.KLF..HHE__20250102T044208Z__20250102T044215Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044208Z_20250102T044215Z/KLF/FN.KLF..HHN__20250102T044208Z__20250102T044215Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044208Z_20250102T044215Z/KLF/FN.KLF..HHZ__20250102T044208Z__20250102T044215Z.mseed  (1 traces)

All windows processed. Done.
UP.PAJU..
Total time: 2025-01-02T04:42:12.032400Z → 2025-01-02T04:42:21.969230Z  (9.93683 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250102T044212Z → 20250102T044221Z ===
  Fetching for: UP.PAJU.*.*
  Warning: can't fetch UP.PAJU.*.*: No data available for request.
HTTP Status code: 204
Detailed response of server:


  No data downloaded for this window.

All windows processed. Done.
FN.RNF..
Total time: 2025-01-02T04:42:20.751990Z → 2025-01-02T04:42:37.124360Z  (16.37237 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250102T044220Z → 20250102T044237Z ===
  Fetching for: FN.RNF.*.*
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..HHZ__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..HHN__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..HHE__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..BHZ__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..BHN__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..BHE__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..LHZ__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..LHN__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..LHE__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..VHZ__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..VHN__20250102T044220Z__20250102T044237Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044220Z_20250102T044237Z/RNF/FN.RNF..VHE__20250102T044220Z__20250102T044237Z.mseed  (1 traces)

All windows processed. Done.
UP.ERTU..
Total time: 2025-01-02T04:42:21.350540Z → 2025-01-02T04:42:38.163940Z  (16.8134 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250102T044221Z → 20250102T044238Z ===
  Fetching for: UP.ERTU.*.*
  Warning: can't fetch UP.ERTU.*.*: No data available for request.
HTTP Status code: 204
Detailed response of server:


  No data downloaded for this window.

All windows processed. Done.
HE.TOF..
Total time: 2025-01-02T04:42:22.459210Z → 2025-01-02T04:42:40.440810Z  (17.9816 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250102T044222Z → 20250102T044240Z ===
  Fetching for: HE.TOF.*.*
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044240Z/TOF/HE.TOF..HHE__20250102T044222Z__20250102T044240Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044240Z/TOF/HE.TOF..HHN__20250102T044222Z__20250102T044240Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044240Z/TOF/HE.TOF..HHZ__20250102T044222Z__20250102T044240Z.mseed  (1 traces)

All windows processed. Done.
FN.SGF..
Total time: 2025-01-02T04:42:22.981090Z → 2025-01-02T04:42:41.093150Z  (18.11206 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250102T044222Z → 20250102T044241Z ===
  Fetching for: FN.SGF.*.*
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..HHZ__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..HHN__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..HHE__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..BHZ__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..BHN__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..BHE__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..LHZ__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..LHN__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..LHE__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..VHZ__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..VHN__20250102T044222Z__20250102T044241Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044222Z_20250102T044241Z/SGF/FN.SGF..VHE__20250102T044222Z__20250102T044241Z.mseed  (1 traces)

All windows processed. Done.
UP.KALU..
Total time: 2025-01-02T04:42:42.470790Z → 2025-01-02T04:42:47.470790Z  (5.0 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250102T044242Z → 20250102T044247Z ===
  Fetching for: UP.KALU.*.*
  Warning: can't fetch UP.KALU.*.*: No data available for request.
HTTP Status code: 204
Detailed response of server:


  No data downloaded for this window.

All windows processed. Done.
UP.LANU..
Total time: 2025-01-02T04:42:27.819480Z → 2025-01-02T04:42:49.251680Z  (21.4322 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250102T044227Z → 20250102T044249Z ===
  Fetching for: UP.LANU.*.*
  Warning: can't fetch UP.LANU.*.*: No data available for request.
HTTP Status code: 204
Detailed response of server:


  No data downloaded for this window.

All windows processed. Done.
HE.HEF..
Total time: 2025-01-02T04:42:28.786080Z → 2025-01-02T04:42:51.507080Z  (22.721 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250102T044228Z → 20250102T044251Z ===
  Fetching for: HE.HEF.*.*
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044228Z_20250102T044251Z/HEF/HE.HEF..HHE__20250102T044228Z__20250102T044251Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044228Z_20250102T044251Z/HEF/HE.HEF..HHN__20250102T044228Z__20250102T044251Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044228Z_20250102T044251Z/HEF/HE.HEF..HHZ__20250102T044228Z__20250102T044251Z.mseed  (1 traces)

All windows processed. Done.
FN.RANF..
Total time: 2025-01-02T04:42:30.880380Z → 2025-01-02T04:42:55.776230Z  (24.89585 s)
Chunk size: 2 minute(s) → 1 window(s)


=== WINDOW 1/1: 20250102T044230Z → 20250102T044255Z ===
  Fetching for: FN.RANF.*.*
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044230Z_20250102T044255Z/RANF/FN.RANF..BHE__20250102T044230Z__20250102T044255Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044230Z_20250102T044255Z/RANF/FN.RANF..BHN__20250102T044230Z__20250102T044255Z.mseed  (1 traces)
  Wrote /home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/waveforms_directory/20250102T044230Z_20250102T044255Z/RANF/FN.RANF..BHZ__20250102T044230Z__20250102T044255Z.mseed  (1 traces)

Traceback (most recent call last):
  File "/home/ad/lxhome/n/ngdeqi/Linux/Documents/DATA11004 Project/eqdet/create_dataset.py", line 7, in <module>
    from obspy.clients.fdsn import Client
  File "/home/ngdeqi/Documents/DATA11004 Project/eqdet/.venv/lib/python3.12/site-packages/obspy/clients/fdsn/__init__.py", line 246, in <module>
    from .routing.routing_client import RoutingClient  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngdeqi/Documents/DATA11004 Project/eqdet/.venv/lib/python3.12/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 25, in <module>
    from ...base import HTTPClient
  File "/home/ngdeqi/Documents/DATA11004 Project/eqdet/.venv/lib/python3.12/site-packages/obspy/clients/base.py", line 55, in <module>
    import requests
  File "/home/ngdeqi/Documents/DATA11004 Project/eqdet/.venv/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/ngdeqi/Documents/DATA11004 Project/eqdet/.venv/lib/python3.12/site-packages/urllib3/__init__.py", line 18, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/home/ngdeqi/Documents/DATA11004 Project/eqdet/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 15, in <module>
    from ._request_methods import RequestMethods
  File "/home/ngdeqi/Documents/DATA11004 Project/eqdet/.venv/lib/python3.12/site-packages/urllib3/_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "/home/ngdeqi/Documents/DATA11004 Project/eqdet/.venv/lib/python3.12/site-packages/urllib3/response.py", line 131, in <module>
    class GzipDecoder(ContentDecoder):
KeyboardInterrupt

KeyboardInterrupt:

#### 4b. Option 2: Query and predict without storing

In [ ]:
result_dir = "results"

# Generate windows to query, identified based on event id and station id (SEED string short)
df_windows = df_picks_eq.drop_duplicates(["Event id", "SEED string short"]) 

cl = Client(ISUH_IP_ADDR)

df_predictions = pd.DataFrame(columns=COLUMNS_Y)

for event_id, seed_string_s, win_start, win_end in zip(df_windows["Event id"], df_windows["SEED string short"], df_windows["Win start"], df_windows["Win end"]):

    network_code = seed_string_s.split(".")[0]
    station_code = seed_string_s.split(".")[1]
    location_code = "00"
    stream_code = "*" # Wildcard to select all streams
    
    # Query waveform from ISUH FDSNWS
    st = cl.get_waveforms(network_code, station_code, location_code, stream_code, win_start, win_end)
    
    try:
        st_predictor(input_modelP=r'eqcct\eqcctone\ModelPS\test_trainer_024.h5',
            input_modelS=r'eqcct\eqcctone\ModelPS\test_trainer_021.h5',
            stinput = st,
            output_dir=WAVEFORM_DIR,
            P_threshold=0.1,
            S_threshold=0.1, 
            number_of_plots=10,
            normalization_mode='std',
            batch_size=1,
            gpuid=None,
            gpu_limit=None,
            overwrite=True)
    except: 
        print(f"Prediction failed for (event id: {event_id}, SEED string short: {seed_string_s})")
        continue
    
    df_prediction = pd.read_csv(Path(WAVEFORM_DIR) / station_code / "X_prediction_results.csv")
    df_predictions = pd.concat([df_predictions, df_prediction])
    
    break

df_predictions.to_csv(Path(WAVEFORM_DIR) / "X_prediction_results.csv")

# data = pd.read_csv('detections_ALPN/ALPN_outputs/X_prediction_results.csv', low_memory=False)
# data.p_arrival_time

# pat=[ii for ii in list(data.p_arrival_time) if type(ii) is str]; #P arrival time
# sat=[ii for ii in list(data.s_arrival_time) if type(ii) is str]; #S arrival time

# plot_traces(st,axoff=1,titleoff=1,ptime= [obspy.UTCDateTime(pat[0]),obspy.UTCDateTime(pat[0]),obspy.UTCDateTime(pat[0])],stime=[obspy.UTCDateTime(sat[0]),obspy.UTCDateTime(sat[0]),obspy.UTCDateTime(sat[0])],figname='test_eqcct_texnet2022yplg.png',dpi=500)

# TODO:
1. Generate noise windows and labels